default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: planning-poker_development

test:
  <<: *default
  database: planning-poker_test

production:
  <<: *default
  database: planning-poker_production
  username: planning-poker
  password: <%= ENV['PLANNING-POKER_DATABASE_PASSWORD'] %>
